#pragma once

#define LEO_PROXCHAT_VERSION_MAJOR 1
#define LEO_PROXCHAT_VERSION_MINOR 0
#define LEO_PROXCHAT_VERSION_PATCH 0

#define LEO_PROXCHAT_STRINGIFY2(x) #x
#define LEO_PROXCHAT_STRINGIFY(x)  LEO_PROXCHAT_STRINGIFY2(x)

#define LEO_PROXCHAT_VERSION_STRING \
    LEO_PROXCHAT_STRINGIFY(LEO_PROXCHAT_VERSION_MAJOR) "." \
    LEO_PROXCHAT_STRINGIFY(LEO_PROXCHAT_VERSION_MINOR) "." \
    LEO_PROXCHAT_STRINGIFY(LEO_PROXCHAT_VERSION_PATCH)

constexpr const char* PLUGIN_VERSION = LEO_PROXCHAT_VERSION_STRING;
